CREATE DATABASE smarterestful;
USE smarterestful;

CREATE table DEF_QUESTION (
	question_id INT(11) NOT NULL AUTO_INCREMENT PRIMARY KEY,
	question VARCHAR(255) NOT NULL DEFAULT '',
	answer VARCHAR(255) NOT NULL DEFAULT ''
);

CREATE TABLE LKP_QUESTION_DISTRACTOR (
	distractor_id INT(11) NOT NULL AUTO_INCREMENT PRIMARY KEY,
	distractor VARCHAR(100) NOT NULL DEFAULT '',
	question_id INT(11) NOT NULL,
	FOREIGN KEY question_foreign_key(question_id)
	REFERENCES DEF_QUESTION(question_id)
	ON UPDATE CASCADE
	ON DELETE CASCADE
);